import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "@/styles/globals.css";

import Navbar from "@/components/navbar";

const prompt = Kumbh_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      { rel: 'icon', url: '/images/favicon.ico' },
      { rel: 'shortcut icon', url: '/images/favicon.ico' }
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/favicon.ico" />
        <link rel="shortcut icon" href="/images/favicon.ico" />
      </head>
      <body className={prompt.className}>
        <div className="sticky top-0 z-10">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}