import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "@/styles/globals.css";

import Navbar from "@/components/navbar";

const prompt = Prompt({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={prompt.className}>
        <div className="sticky top-0 z-10">
          <Navbar />
        </div>
        {children}
        </body>
    </html>
  );
}
